before:
  hooks:
    - go mod download
builds:
  - main: cmd/mcrawl/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
